FROM node:22.3.0
USER root
WORKDIR /app

RUN apt-get update
RUN apt-get -y install locales && \
localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9

RUN rm -rf node_modules

#package.jsonのパスを指定してインストールできる
COPY ./frontend/package.json /app/package.json
COPY ./frontend/package-lock.json /app/package-lock.json
RUN npm install

#フロントエンドの起動
ENTRYPOINT ["npm", "run", "dev"]